### ISSUE TITLE
Consider enabling more clang versions via different versions of Ubuntu in GitHub Actions

### ISSUE THREAD

**Issue by martinmoene** [nonstd-lite/nonstd-lite#75]
See variant-lite PR [Fix failing Clang builds on GitHub Actions (52)](https://github.com/martinmoene/variant-lite/pull/52) by @striezel.

ToDo: decide which versions of clang to include.

Code in .github/ci.yml, only showing two clang versions requiring a different version of Ubuntu:

```yml
    ...
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 11
            os: 'ubuntu-22.04'
          - version: 18
            os: ubuntu-24.04

    runs-on: ${{ matrix.os }}
    ...
```

Versions 11, 12, 13 require ubuntu-22.04, versions 14, 16, 17, 18, 19 are on ubuntu-24.04.

Plan:

- [x] lest
- [x] active-lite
- [x] any-lite
- [x] atomic-lite
- [x] bit-lite
- [x] boolean-lite
- [x] byte-lite
- [x] expected-lite
- [x] indirect-value-lite (see also value-ptr-lite)
- [x] invoke-lite
- [x] jthread-lite
- [x] observer-ptr-lite
- [x] optional-bare
- [x] optional-lite
- [x] optional-fun-lite
- [x] ring-span-lite
- [x] scope-lite
- [x] span-lite
- [x] status-value-lite
- [x] string-lite
- [x] string-non-lite
- [x] string-view-lite
- [x] type-lite
- [x] value-ptr-lite (see also indirect-value-lite)
- [x] variant-lite (revisit)

Other:

- rpc-lite

**Comment by striezel** [comment]
> ToDo: decide which versions of clang to include.

Seeing that GitHub Actions uses Ubuntu-based runners, let's take a look at the Clang versions that the different Ubuntu LTS releases (20.04, 22.04, and 24.04) offer at the moment.

Ubuntu 20.04 has packages for:
* Clang 6.0.1: [clang-6.0](https://packages.ubuntu.com/focal/clang-6.0)
* Clang 7.0.1: [clang-7](https://packages.ubuntu.com/focal/clang-7)
* Clang 8.0.1: [clang-8](https://packages.ubuntu.com/focal/clang-8)
* Clang 9.0.1: [clang-9](https://packages.ubuntu.com/focal/clang-9)
* Clang 10.0.0: [clang-10](https://packages.ubuntu.com/focal/clang-10) _(installed on GHA's `ubuntu-20.04` image by default)_
* Clang 11.0.0: [clang-11](https://packages.ubuntu.com/focal-updates/clang-11) _(installed on GHA's `ubuntu-20.04` image by default)_
* Clang 12.0.0: [clang-12](https://packages.ubuntu.com/focal/clang-12) _(installed on GHA's `ubuntu-20.04` image by default)_
* Clang 18.1.8: [clang-18](https://packages.ubuntu.com/focal/clang-18)

Ubuntu 22.04 has packages for:
* Clang 11.1.0: [clang-11](https://packages.ubuntu.com/jammy/clang-11)
* Clang 12.0.1: [clang-12](https://packages.ubuntu.com/jammy/clang-12)
* Clang 13.0.1: [clang-13](https://packages.ubuntu.com/jammy/clang-13) _(installed on GHA's `ubuntu-22.04` image by default)_
* Clang 14.0.0: [clang-14](https://packages.ubuntu.com/jammy/clang-14) _(installed on GHA's `ubuntu-22.04` image by default)_
* Clang 15.0.7: [clang-15](https://packages.ubuntu.com/jammy/clang-15) _(installed on GHA's `ubuntu-22.04` image by default)_

Ubuntu 24.04 has packages for:
* Clang 14.0.6: [clang-14](https://packages.ubuntu.com/noble/clang-14)
* Clang 15.0.7: [clang-15](https://packages.ubuntu.com/noble/clang-15)
* Clang 16.0.6: [clang-16](https://packages.ubuntu.com/noble/clang-16) _(installed on GHA's `ubuntu-24.04` image by default)_
* Clang 17.0.6: [clang-17](https://packages.ubuntu.com/noble/clang-17) _(installed on GHA's `ubuntu-24.04` image by default)_
* Clang 18.1.3: [clang-18](https://packages.ubuntu.com/noble/clang-18)  _(installed on GHA's `ubuntu-24.04` image by default)_
* Clang 19.1.1: [clang-19](https://packages.ubuntu.com/noble-updates/clang-19)

That does not mean all these versions are installed from the start. In fact, only those marked "_installed on GHA's `ubuntu-2x.04` image by default_" are. But it means that those versions can be installed relatively easy without much hassle.

Technically, that would allow to have tests for each major version of Clang from 6.x to 19.x on GHA. However, that may be overkill for some or even most cases. It would look like this:

```
    ...
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 6
            os: ubuntu-20.04
          - version: 7
            os: ubuntu-20.04
          - version: 8
            os: ubuntu-20.04
          - version: 9
            os: ubuntu-20.04
          - version: 10
            os: ubuntu-20.04
          - version: 11
            os: ubuntu-22.04
          - version: 12
            os: ubuntu-22.04
          - version: 13
            os: ubuntu-22.04
          - version: 14
            os: ubuntu-24.04
          - version: 15
            os: ubuntu-24.04
          - version: 16
            os: ubuntu-24.04
          - version: 17
            os: ubuntu-24.04
          - version: 18
            os: ubuntu-24.04
          - version: 19
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    ...
```

Next thing is that the standard security support for Ubuntu 20.04 will end in April 2025. That usually means that GitHub will remove the corresponding image (`ubuntu-20.04`) a while after that. In other words: In the long run it's not useful to test the Clang versions which are only avaible on Ubuntu 20.04, because the GitHub runner image will be removed "soon<sup>TM</sup>". (If those older versions really need to be tested after the future removal of `ubuntu-20.04`, one could still switch to Docker containers of Ubuntu 20.04, but that would make the workflow file a bit more complicated.)

So as a general rule of thumb new workflow files should probably start with Clang 11. That is the oldest Clang version available in Ubuntu 22.04 and thus will still be available after GitHub decides to remove the `ubuntu-20.04` runner image.
